Watching for file changes with StatReloader
Intento de inicio de sesión para el correo: allison@elpoli.edu.co
Tipo de usuario: estudiante, Tabla: ESTUDIANTES
Ejecutando query: 
                    SELECT * FROM ESTUDIANTES
                    WHERE CORREO_ESTUDIANTE = %s
                 con parámetro: allison@elpoli.edu.co
Usuario no encontrado para el correo: allison@elpoli.edu.co
Watching for file changes with StatReloader
Intento de inicio de sesión para el correo: allison@elpoli.edu.co
Tipo de usuario: estudiante, Tabla: ESTUDIANTES
Ejecutando query: 
                    SELECT * FROM ESTUDIANTES
                    WHERE CORREO_ESTUDIANTE = %s
                 con parámetro: allison@elpoli.edu.co
Usuario no encontrado para el correo: allison@elpoli.edu.co
C:\Users\allil\OneDrive\Escritorio\Octoocourse\blog\settings.py changed, reloading.
Watching for file changes with StatReloader
Intento de inicio de sesión para el correo: allison@elpoli.edu.co
Tipo de usuario: estudiante, Tabla: ESTUDIANTES
Ejecutando query: 
                    SELECT * FROM ESTUDIANTES
                    WHERE CORREO_ESTUDIANTE = %s
                 con parámetro: allison@elpoli.edu.co
Usuario no encontrado para el correo: allison@elpoli.edu.co
C:\Users\allil\OneDrive\Escritorio\Octoocourse\blog\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6363
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
"GET /login/ HTTP/1.1" 200 2150
Intento de inicio de sesión para el correo: allison@elpoli.edu.co
Tipo de usuario: estudiante, Tabla: ESTUDIANTES
Ejecutando query: 
                    SELECT * FROM ESTUDIANTES
                    WHERE CORREO_ESTUDIANTE = %s
                 con parámetro: allison@elpoli.edu.co
Usuario no encontrado para el correo: allison@elpoli.edu.co
"POST /login/ HTTP/1.1" 200 2150
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6363
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
"GET /login/ HTTP/1.1" 200 2150
Correo procesado: 'allison@elpoli.edu.co'
Intento de inicio de sesión para el correo: allison@elpoli.edu.co
Tipo de usuario: estudiante, Tabla: ESTUDIANTES
Ejecutando query: 
                    SELECT * FROM ESTUDIANTES
                    WHERE TRIM(CORREO_ESTUDIANTE) = %s
                 con parámetro: allison@elpoli.edu.co
Usuario encontrado: (1023629824, 'dni                      ', 'Allison                                           ', 'Serna                                             ', 'allison@elpoli.edu.co                             ', datetime.datetime(2006, 5, 23, 0, 0), 'pbkdf2_sha256$870000$upSckQVmKRawmuOQpM8y7j$WT0b5yKMQBvWsIEB2wG/YpXhrAARGe0IMZXozfgX0Ls=')
Índice del campo de contraseña: 6
Contraseña almacenada: pbkdf... (primeros 5 caracteres)
Inicio de sesión exitoso para allison@elpoli.edu.co
Error de inicio de sesión: Reverse for '{% url 'Inicio' %}' not found. '{% url 'Inicio' %}' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py", line 72, in inicioS
    return redirect(redirect_url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '{% url 'Inicio' %}' not found. '{% url 'Inicio' %}' is not a valid view function or pattern name.
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\oracle\base.py", line 577, in execute
    return self.cursor.execute(query, self._param_generator(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\oracledb\cursor.py", line 710, in execute
    impl.execute(self)
  File "src\\oracledb\\impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\\oracledb\\impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src\\oracledb\\impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
oracledb.exceptions.DatabaseError: ORA-01658: no se ha podido crear extensión INITIAL para el segmento en el tablespace TS_OCTOOCOURSE
Help: https://docs.oracle.com/error-help/db/ora-01658/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 121, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 74, in create
    self.save(must_create=True)
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 127, in save
    obj.save(
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\oracle\base.py", line 577, in execute
    return self.cursor.execute(query, self._param_generator(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\oracledb\cursor.py", line 710, in execute
    impl.execute(self)
  File "src\\oracledb\\impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\\oracledb\\impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src\\oracledb\\impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
django.db.utils.DatabaseError: ORA-01658: no se ha podido crear extensión INITIAL para el segmento en el tablespace TS_OCTOOCOURSE
Help: https://docs.oracle.com/error-help/db/ora-01658/
"POST /login/ HTTP/1.1" 500 183371
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6363
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
"GET /login/ HTTP/1.1" 200 2150
Correo procesado: 'allison@elpoli.edu.co'
Intento de inicio de sesión para el correo: allison@elpoli.edu.co
Tipo de usuario: estudiante, Tabla: ESTUDIANTES
Ejecutando query: 
                    SELECT * FROM ESTUDIANTES
                    WHERE TRIM(CORREO_ESTUDIANTE) = %s
                 con parámetro: allison@elpoli.edu.co
Usuario encontrado: (1023629824, 'dni                      ', 'Allison                                           ', 'Serna                                             ', 'allison@elpoli.edu.co                             ', datetime.datetime(2006, 5, 23, 0, 0), 'pbkdf2_sha256$870000$upSckQVmKRawmuOQpM8y7j$WT0b5yKMQBvWsIEB2wG/YpXhrAARGe0IMZXozfgX0Ls=')
Índice del campo de contraseña: 6
Contraseña almacenada: pbkdf... (primeros 5 caracteres)
Inicio de sesión exitoso para allison@elpoli.edu.co
Error de inicio de sesión: Reverse for '{% url 'Inicio' %}' not found. '{% url 'Inicio' %}' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py", line 73, in inicioS
    else:
          
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '{% url 'Inicio' %}' not found. '{% url 'Inicio' %}' is not a valid view function or pattern name.
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\oracle\base.py", line 577, in execute
    return self.cursor.execute(query, self._param_generator(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\oracledb\cursor.py", line 710, in execute
    impl.execute(self)
  File "src\\oracledb\\impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\\oracledb\\impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src\\oracledb\\impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
oracledb.exceptions.DatabaseError: ORA-01658: no se ha podido crear extensión INITIAL para el segmento en el tablespace TS_OCTOOCOURSE
Help: https://docs.oracle.com/error-help/db/ora-01658/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 121, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 74, in create
    self.save(must_create=True)
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 127, in save
    obj.save(
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\oracle\base.py", line 577, in execute
    return self.cursor.execute(query, self._param_generator(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\oracledb\cursor.py", line 710, in execute
    impl.execute(self)
  File "src\\oracledb\\impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\\oracledb\\impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src\\oracledb\\impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
django.db.utils.DatabaseError: ORA-01658: no se ha podido crear extensión INITIAL para el segmento en el tablespace TS_OCTOOCOURSE
Help: https://docs.oracle.com/error-help/db/ora-01658/
"POST /login/ HTTP/1.1" 500 183371
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\allil\OneDrive\Escritorio\Octoocourse\login\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6363
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
"GET /login/ HTTP/1.1" 200 2150
"GET /register/ HTTP/1.1" 200 5692
"GET /static/register/js/seleccion.js HTTP/1.1" 304 0
"GET /static/register/css/styler.css HTTP/1.1" 304 0
"GET /static/register/img/empresa.jpg HTTP/1.1" 304 0
"GET /static/register/img/estudiante.jpg HTTP/1.1" 304 0
"GET /static/register/css/%7B%%20static%20%22register/img/fondopulpito.png%22%20%%7D HTTP/1.1" 404 2023
"POST /register/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 2150
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\oracle\base.py", line 577, in execute
    return self.cursor.execute(query, self._param_generator(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\oracledb\cursor.py", line 710, in execute
    impl.execute(self)
  File "src\\oracledb\\impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\\oracledb\\impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src\\oracledb\\impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
oracledb.exceptions.DatabaseError: ORA-01658: no se ha podido crear extensión INITIAL para el segmento en el tablespace TS_OCTOOCOURSE
Help: https://docs.oracle.com/error-help/db/ora-01658/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 121, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 74, in create
    self.save(must_create=True)
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\contrib\sessions\backends\db.py", line 127, in save
    obj.save(
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\django\db\backends\oracle\base.py", line 577, in execute
    return self.cursor.execute(query, self._param_generator(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allil\OneDrive\Escritorio\Octoocourse\entornoVirtual\Lib\site-packages\oracledb\cursor.py", line 710, in execute
    impl.execute(self)
  File "src\\oracledb\\impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\\oracledb\\impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src\\oracledb\\impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
django.db.utils.DatabaseError: ORA-01658: no se ha podido crear extensión INITIAL para el segmento en el tablespace TS_OCTOOCOURSE
Help: https://docs.oracle.com/error-help/db/ora-01658/
"POST /login/ HTTP/1.1" 500 183326
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6363
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
"GET /login/ HTTP/1.1" 200 2150
"POST /login/ HTTP/1.1" 302 0
"GET /empresa/ HTTP/1.1" 200 4063
"GET /static/empresa/css/InicioE.css HTTP/1.1" 304 0
"GET /static/empresa/css/fondo.css HTTP/1.1" 304 0
"GET /static/empresa/img/fonditoE.jpg HTTP/1.1" 304 0
"GET /static/empresa/css/footerE.css HTTP/1.1" 304 0
"GET /static/empresas/js/navBarE.js.js HTTP/1.1" 404 1889
"GET /static/empresa/css/navBarE.css HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 6363
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
"GET /login/ HTTP/1.1" 200 2150
"GET /register/ HTTP/1.1" 200 5692
"GET /static/register/css/%7B%%20static%20%22register/img/fondopulpito.png%22%20%%7D HTTP/1.1" 404 2023
"POST /register/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 2150
"POST /login/ HTTP/1.1" 302 0
"GET /estudiantes/ HTTP/1.1" 200 7035
"GET /static/estudiantes/css/Colores.css HTTP/1.1" 404 1895
C:\Users\allil\OneDrive\Escritorio\Octoocourse\blog\settings.py changed, reloading.
